#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Name: Package Init
Author: K4YT3X
Date Created: September 15, 2022
Last Modified: September 15, 2022
"""

__version__ = "1.0.0"

# flake8: noqa
# let flake8 ignore this file to avoid F401 warnings
# generated by the following lines
from .sds_submaker import SdsSubMaker
